### ISSUE TITLE
Export circuit network values

### ISSUE THREAD

**Issue by liftM** [liftM/fRPC#1]
Use `game.write_file` to export information, then read the files externally.

## Tasks

- [x] Create entity and item @liftM 
- [x] Implement circuit network signal exporting @liftM 
- [x] Create recipe and technology
- [ ] Create custom artwork
- [x] Implement sidecar network signal reading
- [x] Implement sidecar log rotation
- [x] Design and implement sidecar HTTP API
- [x] Document development environment setup instructions
- [ ] Set up Dockerfile for reproducible deployment

## Prior art

- https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.write_file
- https://github.com/ncabatoff/promfacto
- https://github.com/schaeftide/factorio-statistic
- https://www.reddit.com/r/factorio/comments/9txbd8/trying_to_run_a_basic_script_outputting_my/
- https://medium.com/expected-behavior/instrumentorio-custom-monitoring-for-factorio-or-anything-4c5d63fecdd0

**Comment by elldritch** [comment]
Closing as complete, since this is mostly implemented. Remaining items will be broken out into separate tickets.
